name: Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: |
        mkdir output_folder
        for folder in source_folder1 source_folder2; do
          for file in $folder/*.md; do
            pandoc "$file" -o "output_folder/$(basename "${file%.*}").pdf"
          done
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload PDFs to Release
      id: upload_assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output_folder
        asset_name: PDF_Files
        asset_content_type: application/pdf
